### ISSUE TITLE
Combine efforts with Spring Cloud Contract?

### ISSUE THREAD

**Issue by dsyer** [ePages-de/restdocs-wiremock#29]
Some work has been done on a slightly different implementation of some of the features in this project at https://github.com/spring-cloud/spring-cloud-contract. (We have talked about it moving into Spring Boot or Spring Test at some point in the future as well.) Would the authors of this library be interested in collaborating over there, and bringing some of the ideas and energy from this project to that one? My email address is easy to find if you want to use a back channel to discuss anything.

Cc @marcingrzejszczak.

**Comment by otrosien** [comment]
Closed: We keep in touch with regards to this subject.
