### ISSUE TITLE
com.epages:wiremock-spring-boot-starter not available in jcenter after new version release

### ISSUE THREAD

**Issue by lanwen** [ePages-de/restdocs-wiremock#45]
I use only this module as dependency in my tests:

```xml
<dependency>
<groupId>com.epages</groupId>
<artifactId>wiremock-spring-boot-starter</artifactId>
<version>0.7.17</version>
<scope>test</scope>
</dependency>
```

but i catch a dependency resolution error on new version releases (can be reproduced with `0.7.16`)

**Comment by NicoTexas** [comment]
https://bintray.com/epages/maven/wiremock-spring-boot-starter

pom.xml is missing from version 0.7.13 and up.

https://bintray.com/epages/maven/wiremock-spring-boot-starter/0.7.12 seems fine

**Comment by otrosien** [comment]
@NicoTexas it's that commit. It's most likely the bintray plugin not being properly aware of the new gradle software model DSL.

**Comment by otrosien** [comment]
@NicoTexas  @lanwen hold on, we're in the process of making a new release including the  pom.xmls.

**Comment by jensfischerhh** [comment]
https://bintray.com/epages/maven/wiremock-spring-boot-starter/0.7.18 is a thing now.

**Comment by otrosien** [comment]
something's strange still..

https://bintray.com/epages/maven/wiremock-spring-boot-starter/0.7.18#files/com/epages/wiremock-spring-boot-starter vs.  https://bintray.com/epages/maven/restdocs-wiremock/0.7.18#files/com/epages/wiremock-spring-boot-starter

**Comment by otrosien** [comment]
but it seems to work. I just created a sample project and pulled in the latest wiremock-spring-boot-starter.
