### ISSUE TITLE
Spring Boot 2.0 compatibility

### ISSUE THREAD

**Issue by otrosien** [ePages-de/restdocs-wiremock#62]
Epic for work on Spring Boot 2.0 compatibility.

**Comment by Izakey** [comment]
@otrosien Please could you kindly help out with #61 ?

**Comment by mduesterhoeft** [comment]
@otrosien Just gave it a try and it seems that `restdocs-wiremock` works fine with spring-boot 2.0.0.RELEASE (which is using spring-restdocs 2.0.0.RELEASE).

**Comment by snicoll** [comment]
Relates to https://github.com/spring-projects/spring-boot/issues/13510

**Comment by mduesterhoeft** [comment]
@snicoll @otrosien it looks like the starter also works in spring boot 2.0
I could run the examples with spring boot 2.0 

See https://github.com/ePages-de/restdocs-wiremock/tree/spring-boot-2.0

**Comment by mduesterhoeft** [comment]
The question that remains is if we want to move this project to spring boot 2.0 already. @otrosien what do you think?

**Comment by otrosien** [comment]
👍 ... Is epages ready for 2.0?

**Comment by snicoll** [comment]
I am a bit confused. Do you have a CI or something that makes sure it works with the latest 2.x release?

**Comment by mduesterhoeft** [comment]
@snicoll not yet - I just created a [branch](https://github.com/ePages-de/restdocs-wiremock/tree/spring-boot-2.0) - updated the sample application to use spring boot 2 and ran the tests. That worked fine without touching the actual code of the starter or the spring-restdocs integration.

I think we will shortly upgrade the project to spring boot 2 completely.

But if you need/expect sth else please let me know.
