### ISSUE TITLE
Bring project up to date

### ISSUE THREAD

**Issue by flanaras** [ePages-de/restdocs-wiremock#68]
This project runs on old libraries and technologies.
I would like to motivate to bring it up to date, including

- update gradle :heavy_check_mark:  #70 
  - support Java 11
  - use `library` and `implementation` directives instead of `compile`
- update dependencies
  - gradle plugins
  - java libraries
  - Spring related
    - multi branch for different versions of Spring?
- update Java (Java 11 is supported in Spring Boot 2.1).
- support JUnit 5
- support Java 11 modules
- update readme

**Comment by jmewes** [comment]
Many people still use Java 8. So for an open source project it makes sense to keep JDK 8 as minimum requirment.

![The_State_of_Java](https://user-images.githubusercontent.com/5235584/110652541-c1c9e180-81bc-11eb-9f4c-229a67240464.png)

https://vaadin.com/blog/the-state-of-java

**Comment by flanaras** [comment]
You are right, what we can do is compile with Java 11 and set `targetCompatibility = JavaVersion.VERSION_1_8`, to support Java 8 but be able to adapt to newer Java versions.
